package resources

import (
	"errors"
	"fmt"
	"os"
	"path"
	"regexp"
	"strconv"
	"strings"
	"time"

	"github.com/jiangmuran/vibepanel/internal/cgroup"
	"github.com/jiangmuran/vibepanel/internal/sysmon"
)

// The shape of the scope, which the panel builds and keeps:
//
//	vibepanel-sessions.scope/      MemoryMax backstop, set by systemd; the
//	│                              panel cannot write it without root
//	└── pool/                      memory.max = the budget; the panel's policy
//	    ├── tmux/                  the tmux server, with memory.min, so the
//	    │                          terminals keep drawing while a session thrashes
//	    ├── other/                 anything that cannot be traced to a session
//	    └── s-<tmux name>/         one per session: its memory, its pressure,
//	                               its freezer
//
// The pool exists because the scope's own memory.max belongs to systemd:
// delegation hands over the inside of a cgroup, not its limits, which is the
// kernel's way of stopping a delegated tree from raising its own ceiling. So
// the ceiling the person sets on the page goes one level down.

const (
	poolName    = "pool"
	tmuxLeaf    = "tmux"
	otherLeaf   = "other"
	sessionLeaf = "s-"
)

// wantControllers are enabled wherever they are available. io is often not
// delegated to a user manager, and cgroup.Enable skips what is missing rather
// than failing the lot.
var wantControllers = []string{"cpu", "io", "memory", "pids"}

// leafName guards the one place a name from outside reaches a path. Session
// tmux names are generated by the panel, but a name here that could contain a
// slash is a mkdir somewhere else.
var leafName = regexp.MustCompile(`^[A-Za-z0-9_.-]{1,80}$`)

// Layout is the scope once found.
type Layout struct {
	Scope cgroup.Dir
	Pool  cgroup.Dir
}

// Tmux is the tmux server's leaf.
func (l Layout) Tmux() cgroup.Dir { return l.Pool.Child(tmuxLeaf) }

// Other is where unattributed processes wait.
func (l Layout) Other() cgroup.Dir { return l.Pool.Child(otherLeaf) }

// Session is a session's leaf, by tmux name.
func (l Layout) Session(tmuxName string) (cgroup.Dir, bool) {
	if !leafName.MatchString(tmuxName) {
		return "", false
	}
	return l.Pool.Child(sessionLeaf + tmuxName), true
}

// Why the scope is not usable, as codes the page turns into sentences.
var (
	ErrNotInScope   = errors.New("resources: the tmux server is not in the sessions scope")
	ErrNotDelegated = errors.New("resources: the sessions scope is not delegated to this user")
)

// Find locates the scope from the tmux server's cgroup.
//
// From the server rather than from systemd: the server is the thing that has
// to be inside it, and asking systemd would say where a scope is without
// saying whether the processes are.
func Find(scopeName string, serverPID int) (Layout, error) {
	rel, err := cgroup.Of(serverPID)
	if err != nil {
		return Layout{}, err
	}
	i := strings.Index(rel+"/", "/"+scopeName+"/")
	if i < 0 {
		return Layout{}, ErrNotInScope
	}
	scope := cgroup.At(rel[:i+1+len(scopeName)])
	if !scope.Delegated() {
		return Layout{}, ErrNotDelegated
	}
	return Layout{Scope: scope, Pool: scope.Child(poolName)}, nil
}

// Build makes the layout exist: the pool and its fixed leaves, nothing left
// directly in the scope or the pool, and controllers enabled in both.
//
// Idempotent, and cheap when there is nothing to do, because it runs on every
// tick: a process can land directly in the scope at any time (adoption of a
// server that forked before it was moved, or the root helper writing
// leftovers), and cgroup v2 refuses controllers below a cgroup with a process
// in it.
func (l Layout) Build(serverPID int) error {
	for _, d := range []cgroup.Dir{l.Pool, l.Tmux(), l.Other()} {
		if err := d.Ensure(); err != nil {
			return err
		}
	}
	for _, d := range []cgroup.Dir{l.Scope, l.Pool} {
		if err := evacuate(d, l, serverPID); err != nil {
			return err
		}
		if err := d.Enable(wantControllers...); err != nil {
			// A process forked into d between the evacuation and the write.
			// Once more; a second failure is reported, and the next tick tries
			// again.
			if eerr := evacuate(d, l, serverPID); eerr != nil {
				return eerr
			}
			if err := d.Enable(wantControllers...); err != nil {
				return err
			}
		}
	}
	// The tmux server draws every terminal. Its pages are the last thing that
	// should be reclaimed when a session fills the pool, and memory.min is
	// what says so to the kernel. A fixed amount rather than its usage: the
	// server's own growth is scrollback, bounded by history-limit.
	if l.Tmux().Exists() {
		_ = l.Tmux().SetUint("memory.min", 256*mib)
		_ = l.Tmux().SetUint("cpu.weight", 1000)
	}
	return nil
}

// evacuate moves every process sitting directly in d into a leaf.
func evacuate(d cgroup.Dir, l Layout, serverPID int) error {
	pids, err := d.Procs()
	if err != nil {
		return err
	}
	for _, pid := range pids {
		to := l.Other()
		if pid == serverPID {
			to = l.Tmux()
		}
		if err := to.Move(pid); err != nil {
			return fmt.Errorf("resources: move %d to %s: %w", pid, to.Rel(), err)
		}
	}
	return nil
}

// Procs reads a process. Lazy, and memoised for one tick by LazyProcs: the
// governor runs every two seconds, and reading every entry in /proc to sort the
// handful of processes that are not where they belong would be most of its
// cost on a machine with a couple of thousand processes.
type Procs func(pid int) (sysmon.Proc, bool)

// LazyProcs is a Procs that reads each pid at most once.
func LazyProcs() Procs {
	seen := map[int]sysmon.Proc{}
	missing := map[int]bool{}
	return func(pid int) (sysmon.Proc, bool) {
		if p, ok := seen[pid]; ok {
			return p, true
		}
		if missing[pid] {
			return sysmon.Proc{}, false
		}
		p, ok := sysmon.ReadProc(pid)
		if ok {
			seen[pid] = p
		} else {
			missing[pid] = true
		}
		return p, ok
	}
}

// Pane is one session's pane, as the poller last saw it.
type Pane struct {
	TmuxName string
	PID      int
	// ID is tmux's pane id, "%12", which a process started in the pane carries
	// in TMUX_PANE for as long as it lives -- including after it has been
	// reparented away from the pane by nohup, setsid or a double fork.
	ID string
}

// Sort puts each process in the session it belongs to.
//
// Two ways to belong, tried in order. A process descended from a pane's
// process is that pane's, which covers almost everything. A process that has
// left the tree -- a daemonised dev server, a `nohup make verify &` -- still
// carries TMUX_PANE in its environment, and that is checked for the few that
// the first test misses.
//
// Only processes in the tmux and other leaves are considered. One already in a
// session's leaf stays there: it can only have got there by being sorted, and
// a process whose parent was sorted is born in the right place.
func (l Layout) Sort(panes []Pane, serverPID int, procs Procs) (moved int) {
	byPID := make(map[int]string, len(panes))
	byID := make(map[string]string, len(panes))
	for _, p := range panes {
		if p.PID > 0 {
			byPID[p.PID] = p.TmuxName
		}
		if p.ID != "" {
			byID[p.ID] = p.TmuxName
		}
	}
	up, _ := uptimeTicks()
	for _, leaf := range []cgroup.Dir{l.Tmux(), l.Other()} {
		pids, err := leaf.Procs()
		if err != nil {
			continue
		}
		for _, pid := range pids {
			if pid == serverPID {
				continue
			}
			name := ancestorPane(pid, byPID, procs)
			if name == "" {
				name = paneFromEnv(pid, serverPID, byID)
			}
			if name == "" {
				// A pane the poller has not listed yet sits in the tmux leaf
				// for a tick. Left there briefly rather than moved to other,
				// where it would be charged to nobody; after a while it is
				// not a pane that is about to be listed, it is something the
				// server spawned (run-shell, a hook) and other is right.
				if p, ok := procs(pid); ok && leaf == l.Tmux() && youngerThan(p, up, 10*time.Second) {
					continue
				}
				if leaf == l.Tmux() {
					if l.Other().Move(pid) == nil {
						moved++
					}
				}
				continue
			}
			dst, ok := l.Session(name)
			if !ok || dst.Ensure() != nil {
				continue
			}
			if dst.Move(pid) == nil {
				moved++
				raiseOOMScore(pid)
			}
		}
	}
	return moved
}

// Reclaim brings back a pane that tmux moved into a scope of its own.
//
// tmux built with systemd support puts every new pane in a transient
// `tmux-spawn-<uuid>.scope` of the user manager, so that systemd-oomd can kill
// one pane rather than the server. Measured on tmux 3.6 under a user unit: the
// server was in the pool and every pane was beside the sessions' scope rather
// than in it, outside the budget and outside everything this package measures.
// It only happens where tmux can reach the user bus, which a system unit's
// tmux cannot.
//
// Only a scope of exactly that name, beside ours: the same user manager, so
// the move is permitted, and nothing else anybody has put there.
func (l Layout) Reclaim(p Pane) (moved int) {
	rel, err := cgroup.Of(p.PID)
	if err != nil {
		return 0
	}
	if !tmuxSpawnBeside(rel, l.Scope.Rel()) {
		return 0
	}
	dst, ok := l.Session(p.TmuxName)
	if !ok || dst.Ensure() != nil {
		return 0
	}
	pids, err := cgroup.At(rel).Procs()
	if err != nil {
		return 0
	}
	for _, pid := range pids {
		if dst.Move(pid) == nil {
			moved++
			raiseOOMScore(pid)
		}
	}
	return moved
}

// tmuxSpawnBeside reports whether rel is a scope tmux made for a pane, in the
// same slice as the sessions' scope.
func tmuxSpawnBeside(rel, scope string) bool {
	if strings.HasPrefix(rel+"/", scope+"/") || path.Dir(rel) != path.Dir(scope) {
		return false
	}
	base := path.Base(rel)
	return strings.HasPrefix(base, "tmux-spawn-") && strings.HasSuffix(base, ".scope")
}

// ancestorPane walks up from pid to the first pane process it finds.
func ancestorPane(pid int, byPID map[int]string, procs Procs) string {
	seen := 0
	for cur := pid; cur > 1 && seen < 64; seen++ {
		if name, ok := byPID[cur]; ok {
			return name
		}
		p, ok := procs(cur)
		if !ok {
			return ""
		}
		cur = p.PPID
	}
	return ""
}

// paneFromEnv reads TMUX and TMUX_PANE from a process's environment.
//
// TMUX is checked as well as TMUX_PANE because pane ids are per server: "%3"
// on the person's own tmux is a different pane. TMUX is "socket,pid,session",
// and the pid is this panel's server or the process is not ours to sort.
func paneFromEnv(pid, serverPID int, byID map[string]string) string {
	b, err := os.ReadFile("/proc/" + strconv.Itoa(pid) + "/environ")
	if err != nil {
		return ""
	}
	return paneFromEnviron(b, serverPID, byID)
}

func paneFromEnviron(environ []byte, serverPID int, byID map[string]string) string {
	var tmuxVar, paneVar string
	for _, kv := range strings.Split(string(environ), "\x00") {
		if v, ok := strings.CutPrefix(kv, "TMUX="); ok {
			tmuxVar = v
		} else if v, ok := strings.CutPrefix(kv, "TMUX_PANE="); ok {
			paneVar = v
		}
	}
	parts := strings.Split(tmuxVar, ",")
	if len(parts) < 2 || parts[1] != strconv.Itoa(serverPID) {
		return ""
	}
	return byID[paneVar]
}

// youngerThan reports whether a process started within d of now. starttime is
// in clock ticks since boot, so it is compared against uptime in the same unit.
func youngerThan(p sysmon.Proc, up uint64, d time.Duration) bool {
	if up == 0 || p.Start == 0 {
		return false
	}
	return up >= p.Start && up-p.Start < uint64(d.Seconds()*sysmon.ClockTicks)
}

func uptimeTicks() (uint64, bool) {
	b, err := os.ReadFile("/proc/uptime")
	if err != nil {
		return 0, false
	}
	f := strings.Fields(string(b))
	if len(f) == 0 {
		return 0, false
	}
	secs, err := strconv.ParseFloat(f[0], 64)
	if err != nil {
		return 0, false
	}
	return uint64(secs * sysmon.ClockTicks), true
}

// raiseOOMScore undoes the panel's protection for a session's process.
//
// The system unit sets OOMScoreAdjust=-500 so that the kernel spares the panel
// and the tmux server, and every process the server forks inherits it. Every
// agent was therefore as protected as the panel, and on a machine-wide OOM the
// kernel had no preference between the thing being protected and the thing
// eating the machine. Raising a score needs no privilege; lowering it back
// would, which is why this only ever raises.
func raiseOOMScore(pid int) {
	path := "/proc/" + strconv.Itoa(pid) + "/oom_score_adj"
	b, err := os.ReadFile(path)
	if err != nil {
		return
	}
	if n, err := strconv.Atoi(strings.TrimSpace(string(b))); err == nil && n < 0 {
		_ = os.WriteFile(path, []byte("0"), 0)
	}
}

// Prune removes the leaves of sessions that no longer exist. A leaf with a
// process still in it refuses, which is right: something outlived its pane
// and is still using memory, and the leaf is how that shows up.
func (l Layout) Prune(live map[string]bool) {
	names, err := l.Pool.Children()
	if err != nil {
		return
	}
	for _, n := range names {
		tmuxName, ok := strings.CutPrefix(n, sessionLeaf)
		if !ok || live[tmuxName] {
			continue
		}
		leaf := l.Pool.Child(n)
		if leaf.Frozen() {
			_ = leaf.Freeze(false)
		}
		_ = leaf.Remove()
	}
}
